# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: 
  push: 
    branches: [ dev ] 
    paths: 
    - 'modelcreation.py' 
    - 'app.py'
    - 'result.py'
    - 'lint.py' 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.12 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.12
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install pylint 
    - name: Lint with pylint 
      run: | 
        python lint.py 

    - uses: pre-commit-ci/lite-action@v1.1.0
    if: always()
